### ISSUE TITLE
Set up Sample Hardware

### ISSUE THREAD

**Issue by aturingmachine** [aturingmachine/hockey-elo-tracker#7]
Get an example of the hardware needed to "sign in" set up so we can figure out how to implement it in the final application.

**Comment by kshep15** [comment]
I have designed a prototype RFID card reader using an Arduino Uno board with a MFRC522 (RFID reader board) attached to a breadboard with status LEDs and a piezoelectric speaker.

**Comment by kshep15** [comment]
iteration on the Arduino sketch will be needed for passing the required data to the collection system.
currently the sketch outputs a string containing the Hex value of the user tag/card

**Comment by kshep15** [comment]
Ok no, at the moment I have implimented the open sourced version which uses the  MIFARE Classic 1K 13.56Mhz ISO14443A Format. This format allows us to read a uid from the card to identify a user in the database. An HID brand card reader like the ones we use in the office is on order and will be used in the next revision of the hardware the HID scanner will return a similar uid. The current scanner prototype can be used for development of the back end while the HID scanner is on order.

**Comment by aturingmachine** [comment]
Awesome, I say we can close this then and will make a new one for implementing with the new reader
