### ISSUE TITLE
Implement HID Card Reader

### ISSUE THREAD

**Issue by aturingmachine** [aturingmachine/hockey-elo-tracker#9]
Implement the HID Card reader and get readouts for use in the application.

**Comment by kshep15** [comment]
Card reader delivered today, I will attach it to a prototyping board and start investigating tonight.

**Comment by kshep15** [comment]
HID card reader is now attached to an Arduino Uno which can scan for "Wiegand" wireless standard cards (such as our solstice badges).  the output of the Arduino sends the card length, the FC (facility code) and, CC (card code) in a string over USB for serial read by a computer.
